<a href="https://colab.research.google.com/github/beingshub02/25_days_of_Ml/blob/main/ML_Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Wrangling**

**3.0 Introduction**

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data as a dataframe
dataframe = pd.read_csv(url)

# Show first five rows
dataframe.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**3.1 Creating a Dataframe**


*   Problem
*   You want to create a new dataframe

In [ ]:
# Load library
import pandas as pd

# Create a dictionary
data = {'Name': ['Jacky Jackson', 'Steven Stevenson'],
       'Age': [38, 25],
       'Driver': [True, False]}

# Create a dataframe
dataframe = pd.DataFrame(data)

# Show dataframe
dataframe

               Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

**3.2 Getting Information about the Data**


*   Problem
*   You want to view some characteristics of a Dataframe

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Show two rows
dataframe.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [ ]:
# Show dimension
dataframe.shape

(891, 12)

In [ ]:
# Show statistics
dataframe.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# Show info
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

**3.3 Slicing DataFrames**

*   Problem
*   You need to select a specific subset data or slices of a DataFrame

In [ ]:
# Load library
import pandas as pd

# create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Show top two rows
dataframe.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
 # Select three rows
 dataframe.iloc[1:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [ ]:
 # Select fours rows

**3.4 Selectimg Rows Based on Condtionals**



*   Problem
*   You want to select Dataframe rows based on some condition.

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Show top two rows where column 'sex' is 'female'
dataframe[dataframe['Sex'] == 'female'].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

**3.5 Sortubg Values**



*   Problem
*   You need to sort a dataframe by the values in a column

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Sort dataframe by 'age' in descending order
dataframe.sort_values(by=['Age']).head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master Viljo",male,0.67,1,1,250649,14.5000,NaN,S

**3.6 Replacing Values**


*   Problem
*   You need to replace values in a DataFrame

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Replace values, show two rows
dataframe['Sex'].replace("female", "Woman").head(2)

0     male
1    Woman
Name: Sex, dtype: object

**3.7 Renaming Columns**


*   Problem
*   You want to rename a c

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Rename column, show two rows
dataframe.rename(columns={'Pclass': 'Passenger Class', 'Sex': 'Gender'}).head(2)

,PassengerId,Survived,Passenger Class,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

**3.8 Finding the Minimum, Maximum, Sum, Average, and Count**



*   Problem
*   You want to find the min, max, sum, average, or count of a numeric column.

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Calculate statistics
print('Maximum:', dataframe['Age'].max())
print('Minimum:', dataframe['Age'].min())
print('Mean:', dataframe['Age'].mean())
print('Sum:', dataframe['Age'].sum())
print('Count:', dataframe['Age'].count())

Maximum: 80.0
Minimum: 0.42
Mean: 29.69911764705882
Sum: 21205.17
Count: 714

**3.9 Finding Unique Values**


*   Problem
*   You want to select all unique values in a column.

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Select unique values
dataframe['Sex'].unique()


# Show counts
dataframe['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

**3.10 Handling Missing Values**


*   Problem
*   You want to select missing values in a DataFrame

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

## Select missing values, show two rows
dataframe[dataframe['Age'].isnull()].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S

**3.11 Deleting a Column**


*   Problem
*   You want to delete a column from your DataFrame.

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Delete column
dataframe.drop('Age', axis=1).head(2)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C85,C

**3.12 Deleting a Row**

*   Problem
*   You want to delete one or more rows from a DataFrame.

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Delete rows, show first two rows of output
dataframe[dataframe['Sex'] != 'male'].head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

**3.13 Dropping Duplicate Rows**


*   Problem
*   You want to drop duplicate rows from your DataFrame

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Drop duplicates, show first two rows of output
dataframe.drop_duplicates().head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

**3.14 Grouping Rows by Values**


*   Problem
*   You want to group individual rows according to some shared value.

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Group rows by the values of the column 'Sex', calculate mean
# of each group
dataframe.groupby('Sex').mean(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893

**3.15 Grouping Rows by Time**

*   Problem
*   Grouping Rows by Time

In [ ]:
# Load libraries
import pandas as pd
import numpy as np

# Create date range
time_index = pd.date_range('06/06/2017', periods=100000, freq='30S')

# Create DataFrame
dataframe = pd.DataFrame(index=time_index)

# Create column of random values
dataframe['Sale_Amount'] = np.random.randint(1, 10, 100000)

# Group rows by week, calculate sum per week
dataframe.resample('W').sum()

/tmp/ipykernel_1724/3381545830.py:6: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  time_index = pd.date_range('06/06/2017', periods=100000, freq='30S')

            Sale_Amount
2017-06-11        86526
2017-06-18       101291
2017-06-25       101257
2017-07-02       100434
2017-07-09       101001
2017-07-16        10554

**3.16 Aggregating Operations and Statistics**

*   Problem
*   You need to aggregate an operation over each column (or a set of columns) in a dataframe.

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

dataframe = pd.read_csv(url)

# Get the minimum of numerical columns only
dataframe.select_dtypes(include=['number']).agg("min")

PassengerId    1.00
Survived       0.00
Pclass         1.00
Age            0.42
SibSp          0.00
Parch          0.00
Fare           0.00
dtype: float64

**3.17 Looping over a Column**

*   Problem
*   You want to iterate over every column and apply some action

In [ ]:
# Library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)
# Print first two names uppercased
for name in dataframe['Name'][0:2]:
  print(name.upper())

BRAUND, MR. OWEN HARRIS
CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER)

**3.18 Applying a Function over ALL Elements in a Column**

*   Problem
*   You want to apply some function over all elements in a column

In [ ]:
# Load library
import pandas as pd

# Create URL
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv'

# Load data
dataframe = pd.read_csv(url)

# Group rows, apply function to group
dataframe.groupby('Sex').apply(lambda x: x.count())

/tmp/ipykernel_1293/2500503066.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  dataframe.groupby('Sex').apply(lambda x: x.count())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Sex,,,,,,,,,,,,
female,314,314,314,314,314,261,314,314,314,314,97,312
male,577,577,577,577,577,453,577,577,577,577,107,577

**3.19 Concatenating DataFrames**

*   Problem
*   You want to concatenate two DataFrames.

In [ ]:
# Load library
import pandas as pd

# Create DataFrame
data_a ={'id': ['1','2','3'],
         'first': ['Alex','Amy', 'Allen'],
         'last': ['Anderson', 'Ackerman', 'Ali']}
dataframe_a = pd.DataFrame(data_a,columns=['id', 'first', 'last'])

# create DataFrame
data_b = {'id': ['4', '5', '6'],
          'first': ['Billy', 'Brian', 'Bran'],
          'last': ['Bonder', 'Black', 'Balwner']}
dataframe_b = pd.DataFrame(data_b, columns=['id', 'first', 'last'])

# Concatenate DataFrames by rows
pd.concat([dataframe_a, dataframe_b], axis=0)

  id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali
0  4  Billy    Bonder
1  5  Brian     Black
2  6   Bran   Balwner

**3.20 Merging DataFrames**

*   Problem
*   You want to merge two DataFrames.

In [2]:
# Load library
import pandas as pd

# Create Dataframe
employee_data = {'employee_id': ['1','2','3','4'],
                 'name': ['Amy Jones', 'Allen Keys', 'Alice Bees',
                          'Tim Horton']}
dataframe_employees = pd.DataFrame(employee_data, columns=['employee_id',
                                                            'name'])
# Create  DataFrame
sales_data = {'employee_id': ['3','4','5','6'],
              'total_sales': [23456, 2512, 2345, 1455]}
dataframe_sales = pd.DataFrame(sales_data, columns=['employee_id',
                                                          'total_sales'])

# Merge DataFrames
pd.merge(dataframe_employees, dataframe_sales, on='employee_id')

  employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512